### ISSUE TITLE
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

### ISSUE THREAD

**Issue by CrashLaker** [benc-uk/hcl2-parser#3]
Hi all,

how can i fix this error?

![image](https://user-images.githubusercontent.com/4432491/202924334-03b24f93-da68-44b4-a557-44fb8ea6fb51.png)

    "hcl2-parser": "^1.0.3",
    "webpack": "^5.74.0",
    "webpack-cli": "^4.10.0",
    "webpack-dev-server": "^4.11.1"

$ node --version
v16.13.0

$ npm --version
8.1.0

I installed `npm i --save hcl2-parser`

regards,c.

**Comment by benc-uk** [comment]
Hi, I'm no longer supporting or using this code, sorry!
